# Generated by Django 5.0.3 on 2024-04-03 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_color_variant_cartitems_color_varient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='color_varient',
            new_name='color_variant',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='size_varient',
            new_name='size_variant',
        ),
    ]
