# Generated by Django 5.0.3 on 2024-04-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_color_variant_cartitems_color_varient_and_more'),
        ('products', '0005_coupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorVariant',
            new_name='ColorVarient',
        ),
        migrations.RenameModel(
            old_name='SizeVariant',
            new_name='SizeVarient',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color_variant',
            new_name='color_varient',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_variant',
            new_name='size_varient',
        ),
    ]
